# Generated by Django 2.1.4 on 2018-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_str', models.CharField(max_length=100, verbose_name='cron schedule string')),
                ('name', models.CharField(max_length=50)),
                ('time_window', models.IntegerField(default=0)),
                ('next_run', models.DateTimeField(verbose_name='next time to run')),
                ('last_notified', models.DateTimeField(verbose_name='last time notification received')),
            ],
        ),
    ]
