# Generated by Django 2.1.4 on 2018-12-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_window',
            field=models.IntegerField(default=0, verbose_name='time window (minutes)'),
        ),
    ]
