# Generated by Django 2.1.5 on 2019-01-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
