# Generated by Django 2.1.7 on 2019-02-16 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0002_auto_20190127_1657'),
    ]

    operations = [
        # manually edited to stop Django unneccessarily deleting models
        migrations.RenameField(
            model_name='job',
            old_name='user_group',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='jobgroup',
            old_name='user_group',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_groups',
            new_name='teams',
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_alerts_on',
            field=models.BooleanField(default=True, verbose_name='alerts on for jobs without a team'),
        ),
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='usergroupmembership',
            old_name='group',
            new_name='team'
        ),
        migrations.RenameModel(
            old_name='UserGroupMembership',
            new_name='TeamMembership',
        ),
        
    ]
