# Generated by Django 2.1.7 on 2019-02-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0003_rename_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_failed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last time job failed to notify'),
        ),
    ]
