# Generated by Django 2.1.4 on 2018-12-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0005_auto_20181216_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crontrack.JobGroup'),
        ),
    ]
