# Generated by Django 2.1.7 on 2019-02-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0005_auto_20190222_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobevent',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobevent',
            name='type',
            field=models.CharField(choices=[('F', 'Failure')], default='F', max_length=1),
        ),
    ]
