# Generated by Django 2.1.4 on 2018-12-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0008_auto_20181223_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_notified',
            field=models.DateTimeField(null=True, verbose_name='last time notification received'),
        ),
    ]
