# Generated by Django 2.1.4 on 2019-01-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0009_auto_20181223_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_method',
            field=models.CharField(choices=[('E', 'Email'), ('T', 'Text')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last time notification received'),
        ),
    ]
