# Generated by Django 2.1.4 on 2019-01-20 02:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0010_auto_20190104_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(null=True, blank=True, max_length=128, unique=True),
        ),
    ]
