# Generated by Django 2.1.4 on 2019-01-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0012_auto_20190120_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_alert',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last time alert sent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='alert_buffer',
            field=models.IntegerField(default=1440, verbose_name='time to wait between alerts (min)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alert_method',
            field=models.CharField(choices=[('E', 'Email'), ('T', 'SMS')], default='E', max_length=1),
        ),
    ]
