# Generated by Django 2.1.4 on 2019-01-23 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('crontrack', '0013_auto_20190122_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
