# Generated by Django 2.1.4 on 2019-01-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0016_auto_20190124_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgroup',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crontrack.UserGroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='crontrack.UserGroup'),
        ),
    ]
