# Generated by Django 2.1.4 on 2019-01-24 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crontrack', '0017_auto_20190124_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_alert', models.DateTimeField(blank=True, null=True, verbose_name='last time alert sent')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_alert',
        ),
        migrations.AlterField(
            model_name='job',
            name='time_window',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='time window (minutes)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crontrack.UserGroup'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crontrack.UserGroup'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crontrack.Job'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='alerted_users',
            field=models.ManyToManyField(related_name='job_alert_set', through='crontrack.JobAlert', to=settings.AUTH_USER_MODEL),
        ),
    ]
