# Generated by Django 2.1.5 on 2019-01-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0018_auto_20190124_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_on', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crontrack.UserGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='alert_method',
            field=models.CharField(choices=[('E', 'Email'), ('T', 'SMS'), ('N', 'No alerts')], default='N', max_length=1),
        ),
		migrations.RemoveField(  # Edited by hand (AlterField split into remove and add)
            model_name='profile',
            name='groups',
        ),
        migrations.AddField(  # Edited by hand
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(through='crontrack.UserGroupMembership', to='crontrack.UserGroup'),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crontrack.Profile'),
        ),
    ]
