# Generated by Django 2.1.5 on 2019-01-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0019_auto_20190125_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupmembership',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crontrack.UserGroup'),
        ),
    ]
