# Generated by Django 2.1.5 on 2019-01-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crontrack', '0020_auto_20190125_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_alerts_on',
            field=models.BooleanField(default=True, verbose_name='alerts on for jobs without a user group'),
        ),
        migrations.AlterField(
            model_name='usergroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crontrack.UserGroup'),
        ),
    ]
